FROM node:8.9.1 

RUN mkdir /opt/renew-frontend
WORKDIR /opt/renew-frontend 
COPY package.json package-lock.json ./

RUN npm install 

COPY . /tmp/holding 
RUN rm -rf /tmp/holding/node_modules; cp -Rfv /tmp/holding/* /opt/renew-frontend

CMD npm start

